name: CI

on:
  pull_request:
    branches:
      - main
      - beta

jobs:
  test_build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn test:prod
